### ISSUE TITLE
Define audience on the readme to help tailor the lesson

### ISSUE THREAD

**Issue by elsehow** [elsehow/frp-adventure#2]
> We should probably define audience on the readme to help tailor the lesson. Are you trying to target those who may already know other async coding (spa apps like Angular/Backbone), or someone with little CS background?  

-- @sartaj 

 my instinct is that we should be targeting folks with some JS experience, and some understanding of what an asynchronous event is. 

but, I don't think we need to target people who have a proper CS background, or people who have experience with other frameworks. I feel like, if you know what a callback is and why you need to use one, this tutorial could be for you.

other thoughts?

**Comment by sartaj** [comment]
Word. I agree that someone who at least knows some async should be the audience. 

So for a more concrete image, could we say minimum requirements being as "understanding basic javascript (perhaps passed code academy), made a few interactive websites, plus basic jQuery and jQuery.ajax experience"?

**Comment by elsehow** [comment]
sounds good, I've updated the readme
